<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class InvestigateReport extends Model
{
    use HasFactory;
    use SoftDeletes;

    protected $fillable = [
        'interviewer_name',
        'interview_date',
        'interviewer_designation',
        'interviewer_contact_number',
        'suspected_name',
        'suspected_gender',
        'suspect_age',
        'suspect_occupation',
        'suspect_address',
        'suspect_education',
        'respondent_name',
        'respondent_age',
        'respondent_contact',
        'respondent_address',
        'relationship_with_suspect',
        'healthcare_worker_facility_name',
        'specify_other_name',
        'suspect_contact_with_animals',
        'animal_species',
        'type_of_animal',
        'deceased_date',
        'place_of_exposure',
        'place_of_exposure_address',
        'location_of_bite',
        'number_of_wounds',
        'sign_of_disease',
        'animal_die_exposure',
        'animal_die_date',
        'animal_tested_rabies',
        'animal_vaccinated',
        'treatment_applied',
        'suturesa_applied',
        'reason_for_suturing',
        'rig_infiltration',
        'rabiesVaccineRecieved',
        'RabiesVaccineReceivedYes',
        'rabies_vaccine_received',
        'incomplete_pep',
        'rabies_immunoglobulin',
        'rabies_immunoglobulin_site',
        'brand_name',
        'rig_administration',
        'year_no_of_dose',
        'vaccinated_against_rabies',
        'TT_vaccine',
        'fever',
        'headache',
        'vomiting',
        'muscle_spasm',
        'anorexia',
        'priapism',
        'aerophobia',
        'localized_weakness',
        'confusion',
        'agitation',
        'autonomic_instability',
        'insomnia',
        'malaise',
        'nausea',
        'anxiety',
        'dysphasia',
        'ataxia',
        'seizures',
        'hydrophobia',
        'localized_pain',
        'delirium',
        'aggressiveness',
        'hyperactivity',
        'hypersalivation',
        'symptoms_onset_date',
        'date_of_birth',
        'alive',
        'deceased_die',
        'deceased_die_health_facility_input',
        'deceased_die_other_input',
        'medical_help',
        'hf_1date',
        'hf_2date',
        'hf_3date',
        'laboratory_specific_test',
        'MRI_brain_done',
        'postmortem',
        'copy_of_report',
        'evidence_of_recent_wounds',
        'evidence_of_healed_wounds',
        'certificate_available',
        'death_mentioned',
        'contact_tracking',
        'autopsy_of_additional_cases',
        'family',
        'community',
        'hospital_workers',
        'any_other',
        'animal_suspected_transmitting',
        'probable_rabies',
    ];

    protected $casts = [
        'suspect_education' => 'object',
        'animal_species' => 'object',
        'type_of_animal' => 'object',
        'location_of_bite' => 'object',
        'number_of_wounds' => 'object',
        'sign_of_disease' => 'object',
        'treatment_applied' => 'object',
        'rabies_vaccine_received' => 'object',
        'incomplete_pep' => 'object',
        'laboratory_specific_test' => 'object',
        'family' => 'object',
        'community' => 'object',
        'hospital_workers' => 'object',
        'any_other' => 'object',
        'animal_suspected_transmitting' => 'object',
    ];
}
